disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace

opt_in_rules: # some rules are only opt-in
  - empty_count

included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Example

# configurable rules can be customized from this configuration file
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true
