disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_cast
  - force_try
  - identifier_name
  - line_length
  - type_name

opt_in_rules: # some rules are only opt-in
  - empty_count

included: # paths to include during linting. `--path` is ignored if present.
  - Sources
  - Tests

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - Example

function_body_length:
  warning: 150
  error: 200

cyclomatic_complexity:
  warning: 20
  error: 30

vertical_whitespace:
  max_empty_lines: 2
